### ISSUE TITLE
Show limit

### ISSUE THREAD

**Issue by Mad1San** [RoyTheunissen/Asset-Palette#37] opened 2024-06-03 16:22 UTC
Does not show all assets (

Performance warning: There are more than 100 preview scenes. There might be code not releasing the preview scene after creating it.
UnityEditor.GameObjectInspector:RenderStaticPreview (string,UnityEngine.Object[],int,int)
RoyTheunissen.AssetPalette.PaletteAsset:get_PreviewTexture () (at Library/PackageCache/com.roytheunissen.assetpalette@d67006628a/Editor/Entries/PaletteAsset.cs:74)
RoyTheunissen.AssetPalette.CustomEditors.PaletteAssetDrawer:DrawContents (UnityEngine.Rect,UnityEditor.SerializedProperty,RoyTheunissen.AssetPalette.PaletteAsset) (at Library/PackageCache/com.roytheunissen.assetpalette@d67006628a/Editor/CustomEditors/PaletteAssetDrawer.cs:18)
RoyTheunissen.AssetPalette.CustomEditors.PaletteEntryDrawer`1<RoyTheunissen.AssetPalette.PaletteAsset>:OnGUI (UnityEngine.Rect,UnityEditor.SerializedProperty,RoyTheunissen.AssetPalette.PaletteEntry) (at Library/PackageCache/com.roytheunissen.assetpalette@d67006628a/Editor/CustomEditors/PaletteEntryDrawer.cs:98)
RoyTheunissen.AssetPalette.CustomEditors.PaletteDrawing:DrawGridEntry (UnityEngine.Rect,UnityEditor.SerializedProperty,RoyTheunissen.AssetPalette.PaletteEntry) (at Library/PackageCache/com.roytheunissen.assetpalette@d67006628a/Editor/CustomEditors/PaletteDrawing.cs:52)
RoyTheunissen.AssetPalette.Windows.EntryPanel:DrawGridEntry (int,int,bool&) (at Library/PackageCache/com.roytheunissen.assetpalette@d67006628a/Editor/Windows/EntryPanel.cs:406)
RoyTheunissen.AssetPalette.Windows.EntryPanel:DrawGridEntries (single,bool&) (at Library/PackageCache/com.roytheunissen.assetpalette@d67006628a/Editor/Windows/EntryPanel.cs:367)
RoyTheunissen.AssetPalette.Windows.EntryPanel:DrawEntriesPanel () (at Library/PackageCache/com.roytheunissen.assetpalette@d67006628a/Editor/Windows/EntryPanel.cs:287)
RoyTheunissen.AssetPalette.Windows.AssetPaletteWindow:OnGUI () (at Library/PackageCache/com.roytheunissen.assetpalette@d67006628a/Editor/Windows/AssetPaletteWindow.cs:169)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

Unable to allocate new scene culling mask
UnityEditor.GameObjectInspector:RenderStaticPreview (string,UnityEngine.Object[],int,int)
RoyTheunissen.AssetPalette.PaletteAsset:get_PreviewTexture () (at Library/PackageCache/com.roytheunissen.assetpalette@d67006628a/Editor/Entries/PaletteAsset.cs:74)
RoyTheunissen.AssetPalette.CustomEditors.PaletteAssetDrawer:DrawContents (UnityEngine.Rect,UnityEditor.SerializedProperty,RoyTheunissen.AssetPalette.PaletteAsset) (at Library/PackageCache/com.roytheunissen.assetpalette@d67006628a/Editor/CustomEditors/PaletteAssetDrawer.cs:18)
RoyTheunissen.AssetPalette.CustomEditors.PaletteEntryDrawer`1<RoyTheunissen.AssetPalette.PaletteAsset>:OnGUI (UnityEngine.Rect,UnityEditor.SerializedProperty,RoyTheunissen.AssetPalette.PaletteEntry) (at Library/PackageCache/com.roytheunissen.assetpalette@d67006628a/Editor/CustomEditors/PaletteEntryDrawer.cs:98)
RoyTheunissen.AssetPalette.CustomEditors.PaletteDrawing:DrawGridEntry (UnityEngine.Rect,UnityEditor.SerializedProperty,RoyTheunissen.AssetPalette.PaletteEntry) (at Library/PackageCache/com.roytheunissen.assetpalette@d67006628a/Editor/CustomEditors/PaletteDrawing.cs:52)
RoyTheunissen.AssetPalette.Windows.EntryPanel:DrawGridEntry (int,int,bool&) (at Library/PackageCache/com.roytheunissen.assetpalette@d67006628a/Editor/Windows/EntryPanel.cs:406)
RoyTheunissen.AssetPalette.Windows.EntryPanel:DrawGridEntries (single,bool&) (at Library/PackageCache/com.roytheunissen.assetpalette@d67006628a/Editor/Windows/EntryPanel.cs:367)
RoyTheunissen.AssetPalette.Windows.EntryPanel:DrawEntriesPanel () (at Library/PackageCache/com.roytheunissen.assetpalette@d67006628a/Editor/Windows/EntryPanel.cs:287)
RoyTheunissen.AssetPalette.Windows.AssetPaletteWindow:OnGUI () (at Library/PackageCache/com.roytheunissen.assetpalette@d67006628a/Editor/Windows/AssetPaletteWindow.cs:169)
UnityEngine.GUIUtility:ProcessEvent (int,intptr,bool&)

![image](https://github.com/RoyTheunissen/Asset-Palette/assets/48926648/9fbf4c37-8bd7-4ddc-8837-1e09a91f59cd)

**Comment by Mad1San** [comment] 2024-06-04 08:21
I found a fast-fix

![image](https://github.com/RoyTheunissen/Asset-Palette/assets/48926648/a850197c-bef5-4cf4-914d-a969f8e60be8)

**Comment by RoyTheunissen** [comment] 2024-06-04 09:48
Interesting! I've not seen this one yet myself.

Can you give me some information on how to reproduce it? Happy to have a look at it later.


Thanks for exploring possible fixes by the way👍

**Comment by Mad1San** [comment] 2024-06-05 09:55
To replicate this, I create an empty project in version 2021.3.21f1, create a prefab cube, copy it 100 times, and then add all the prefabs to the palette. This is how this error occurs.

**Comment by RoyTheunissen** [comment] 2024-06-06 14:38
I had time to take a look at it, it seems to be a regression of a bug caused by an optimization.

Reverting that optimization (which is arguably not necessary) seems to fix the issue, I am checking with the original author that he agrees with the change

I also had a look at your suggestion @Mad1San but it seems like that does not always correctly show the _contents_ of the prefab. I seem to get the blue prefab icon as a result instead.

The fix will be merged soon 👍

**Comment by RoyTheunissen** [comment] 2024-06-06 18:41
Using the steps you described I was able to reproduce the issue, and after my fix I was no longer able to reproduce it.

I'm considering it fixed now. Thanks for reporting it!

You can try out the fix in the [latest version](https://github.com/RoyTheunissen/Asset-Palette/releases/tag/v0.4.4).

**Closed as completed by RoyTheunissen** 2024-06-06 18:41 UTC

**Comment by Mad1San** [comment] 2024-06-07 23:46
thank u <3
